[package]
name = "simple-email"
version = "0.1.0"
authors = ["Binlogo <binboy@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.9"
lettre_email = "0.9"